package Ejecutables;


import javax.swing.JFrame;
import modelos.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author agerk
 */
public class MenuJugadores extends javax.swing.JFrame {
 private javax.swing.JComboBox jComboBox1 = new javax.swing.JComboBox<>();
 public static ArrayList <Jokalaria> jokalariak= new ArrayList<Jokalaria>();
 public static Jokalaria j2 = new Jokalaria("");
  private String[] nombres;
  private final File archivomp3;
  private Clip clip;
  private AudioInputStream audioInputStream;
 /**
     * Creates new form Trivial
     */
    public MenuJugadores() {
        initComponents();
        
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        jButton2.setVisible(false);
        archivomp3 = new File (FileSystems.getDefault().getPath("").toAbsolutePath() + "/src/jugar_click.wav");
        
        
        setLocationRelativeTo(null);
        if(jokalariak.isEmpty()){
            initJokalariak();
        }else{
           nombres= new String[jokalariak.size()];
            for(int index =0; index < jokalariak.size(); index ++){
                nombres[index] = jokalariak.get(index).getUname();
                if(jokalariak.get(index).getUname().equals(Trivial2.getJ1().getUname())){
                    jokalariak.set(index,Trivial2.getJ1());
                }
           
        }
      
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 260, -1));
        /*jComboBox1 = new JComboBox(nombres);*/
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(nombres)); 
        }
        
        
    }
    private void initJokalariak(){
        jokalariak.add(new Jokalaria ("Ager")) ;
        jokalariak.add(new Jokalaria ("Raul")) ;
        jokalariak.add(new Jokalaria ("Loiza_09")) ;
        jokalariak.add(new Jokalaria ("MdeManzana")) ;
        jokalariak.add(new Jokalaria ("TitoJaggy")) ;
        nombres= new String[jokalariak.size()];
        for(int index =0; index < jokalariak.size(); index ++){
            nombres[index] = jokalariak.get(index).getUname();
           
        }
      
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 260, -1));
        /*jComboBox1 = new JComboBox(nombres);*/
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(nombres));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setBackground(new java.awt.Color(255, 255, 153));
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonjugar.jpg"))); // NOI18N
        boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 180, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aukeratu jokalari bat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 390, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 310, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sartu jokalariaren izena: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 170, 20));

        jButton1.setText("Berri bat sortu");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 210, -1));

        jButton2.setText("Gehitu");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1154426116-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 601));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        play();
        JFrame ir= new Trivial2();
        ir.setLocationRelativeTo(null);
        ir.setVisible(true);
        this.dispose();
        isSelected();
    }//GEN-LAST:event_boton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           play();
        jComboBox2.setVisible(false);
        jTextField1.setVisible(true);
        jLabel2.setVisible(true);
        jButton2.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void play(){
        try {
            audioInputStream = AudioSystem.getAudioInputStream(archivomp3);            
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);            
            clip.start();
        } catch (LineUnavailableException | IOException| UnsupportedAudioFileException e) {
            System.err.println(e.getMessage());
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        play();
        jokalariak.add(new Jokalaria(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        jButton2.setVisible(false);
        String[] emptyArray = new String[]{};
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(emptyArray));
        setComboBox();
        jComboBox2.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trivial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trivial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trivial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trivial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJugadores().setVisible(true);
                
                
            }
            
        });
        
    }
    public void setComboBox(){
       
        
        nombres= new String[jokalariak.size()];
        for(int index =0; index < jokalariak.size(); index ++){
            nombres[index] = jokalariak.get(index).getUname();
           
        }
      
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 260, -1));
        /*jComboBox1 = new JComboBox(nombres);*/
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(nombres));
        
        
    }

    public static ArrayList<Jokalaria> getJokalariak() {
        return jokalariak;
    }
    public void isSelected(){
        
        for(Jokalaria x : jokalariak){
            if(jComboBox2.getSelectedItem().toString().equals(x.getUname())){
                j2.setUname(x.getUname());
                j2.setSaves(x.getLastSave());
                
            }
        }
        
    }

    public static Jokalaria getJ2() {
        return j2;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
