package Ejecutables;

import java.util.*;
import modelos.*;
import java.lang.Math;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author parra.raul
 */
public class Trivial2 extends javax.swing.JFrame {

    private static Jokalaria j1;
    
    private Partida p1;
    private ArrayList<Galdera> g = new ArrayList<Galdera>();
    private Trivial2 prueba;
    final int LIMITE =6;
    private ArrayList<Galdera> galderaSorta = new ArrayList<Galdera>(LIMITE);
    private final File archivomp3;
    private final File archivo_2;
    private final File archivo_3;
    
    
    private Clip clip;
    private AudioInputStream audioInputStream;

    /**
     * Creates new form Trivial2
     */
    public Trivial2() {
        initComponents();

        initialize();
        createPartida();
        nextRonda();
        agertuFalseatzailea();
        jInternalFrame1.setVisible(false);
        jPanel2.setVisible(false);  
        jPanel_resultado.setVisible(false);
        jButton1.setVisible(false);//asta ke agas lo del fitxategi
        jButton2.setVisible(false);//asta ke agas lo del fitxategi
        
        archivomp3 = new File (FileSystems.getDefault().getPath("").toAbsolutePath() + "/src/click_2.wav");
        archivo_2 = new File (FileSystems.getDefault().getPath("").toAbsolutePath() + "/src/jugar_click.wav");
        archivo_3 = new File (FileSystems.getDefault().getPath("").toAbsolutePath() + "/src/oker.wav");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel_resultado = new javax.swing.JPanel();
        jLabel_amaieraText = new javax.swing.JLabel();
        jLabel_puntuazioaText = new javax.swing.JLabel();
        jLabel_zuzenakText = new javax.swing.JLabel();
        jLabel_zuzenak = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_jokIzena = new javax.swing.JLabel();
        jLabel_okerrak = new javax.swing.JLabel();
        jLabel_resMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmaitzaJokalari = new javax.swing.JLabel();
        jLabelEmaitzaZuzen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEmaitzaOker = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabelResult = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelGaldera = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jButton_erantzun1 = new javax.swing.JButton();
        jButton_erantzun2 = new javax.swing.JButton();
        jButton_erantzun3 = new javax.swing.JButton();
        jButtonItzuli = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonPuntuazioa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_resultado.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_amaieraText.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_amaieraText.setFont(new java.awt.Font("Vladimir Script", 0, 18)); // NOI18N
        jLabel_amaieraText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_amaieraText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_amaieraText.setText("Amaiera! GG");

        jLabel_puntuazioaText.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_puntuazioaText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_puntuazioaText.setText("Puntuazioa:");

        jLabel_zuzenakText.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_zuzenakText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_zuzenakText.setText("Zuzenak:");

        jLabel_zuzenak.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_zuzenak.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Okerrak:");

        jLabel_jokIzena.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_jokIzena.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_okerrak.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_okerrak.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_resMessage.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_resMessage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_resMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resMessage.setToolTipText("");

        javax.swing.GroupLayout jPanel_resultadoLayout = new javax.swing.GroupLayout(jPanel_resultado);
        jPanel_resultado.setLayout(jPanel_resultadoLayout);
        jPanel_resultadoLayout.setHorizontalGroup(
            jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_puntuazioaText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                .addGroup(jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_resultadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_amaieraText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_resultadoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_resMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_okerrak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                                .addGroup(jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                                        .addComponent(jLabel_zuzenakText)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_zuzenak, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_jokIzena, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(95, 95, 95))
        );
        jPanel_resultadoLayout.setVerticalGroup(
            jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_amaieraText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_puntuazioaText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_resultadoLayout.createSequentialGroup()
                        .addComponent(jLabel_jokIzena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_zuzenakText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_zuzenak, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_okerrak, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_resMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabelEmaitzaJokalari.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEmaitzaJokalari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmaitzaJokalari.setForeground(new java.awt.Color(255, 255, 255));

        jLabelEmaitzaZuzen.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEmaitzaZuzen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmaitzaZuzen.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jokalaria:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ZUZENAK:");

        jLabelEmaitzaOker.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEmaitzaOker.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmaitzaOker.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OKERRAK:");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 153));
        jButton4.setText("ITZULI");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEmaitzaJokalari, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmaitzaZuzen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEmaitzaOker, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmaitzaJokalari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmaitzaZuzen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmaitzaOker, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, 180));

        jInternalFrame1.setBackground(new java.awt.Color(0, 0, 0));
        jInternalFrame1.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);

        jLabelResult.setBackground(new java.awt.Color(0, 0, 0));
        jLabelResult.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Ados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 106, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 460, 170));

        jLabelGaldera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelGaldera.setForeground(new java.awt.Color(255, 255, 102));
        jLabelGaldera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelGaldera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 470, 30));

        jLabelImg.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, 50));

        jButton_erantzun1.setBackground(new java.awt.Color(0, 0, 0));
        jButton_erantzun1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_erantzun1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_erantzun1.setBorderPainted(false);
        jButton_erantzun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_erantzun1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_erantzun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, 20));

        jButton_erantzun2.setBackground(new java.awt.Color(0, 0, 0));
        jButton_erantzun2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_erantzun2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_erantzun2.setBorderPainted(false);
        jButton_erantzun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_erantzun2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_erantzun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 20));

        jButton_erantzun3.setBackground(new java.awt.Color(0, 0, 0));
        jButton_erantzun3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_erantzun3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_erantzun3.setBorderPainted(false);
        jButton_erantzun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_erantzun3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_erantzun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 160, 20));

        jButtonItzuli.setBackground(new java.awt.Color(0, 0, 0));
        jButtonItzuli.setForeground(new java.awt.Color(255, 255, 255));
        jButtonItzuli.setText("ITZULI");
        jButtonItzuli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonItzuli.setBorderPainted(false);
        jButtonItzuli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonItzuli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItzuliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonItzuli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 20));

        jButton1.setText("save");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, -1));

        jButtonPuntuazioa.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPuntuazioa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonPuntuazioa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPuntuazioa.setText("PUNTUAZIOA");
        jButtonPuntuazioa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPuntuazioa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPuntuazioa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntuazioaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPuntuazioa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("cargar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/laimagendelaspreguntas2.jpg"))); // NOI18N
        jLabel1.setText("sdfasdfasd");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_erantzun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_erantzun1ActionPerformed
        // TODO add your handling code here:
        jLabelResult.setText("");
        jInternalFrame1.setVisible(false);
        for (int x = 0; x < p1.getGalderak().size(); x++) {
            if (jButton_erantzun1.getText().equals(p1.getGalderak().get(x).getEzuzena())) {
                play_ondo();
                jLabelResult.setText("Erantzun zuzena!!");
                jInternalFrame1.setVisible(true);
                p1.seteZuzenak(p1.geteZuzenak() + 1);
                p1.setRondak(p1.getRondak() + 1);
                p1.getGalderak().get(x).setAgertu(true);
                controlRondas();
                break;
            } else if (jButton_erantzun1.getText().equals(p1.getGalderak().get(x).getEokerra1())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);
            } else if (jButton_erantzun1.getText().equals(p1.getGalderak().get(x).getEokerra2())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);
            }
        }
    }//GEN-LAST:event_jButton_erantzun1ActionPerformed

    private void jButton_erantzun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_erantzun2ActionPerformed
        // TODO add your handling code here:
        jLabelResult.setText("");
        jInternalFrame1.setVisible(false);
        for (int x = 0; x < p1.getGalderak().size(); x++) {
            if (jButton_erantzun2.getText().equals(p1.getGalderak().get(x).getEzuzena())) {
                play_ondo();
                jLabelResult.setText("Erantzun zuzena!!");
                jInternalFrame1.setVisible(true);
                p1.seteZuzenak(p1.geteZuzenak() + 1);
                p1.setRondak(p1.getRondak() + 1);
                p1.getGalderak().get(x).setAgertu(true);
                controlRondas();
                break;
            } else if (jButton_erantzun2.getText().equals(p1.getGalderak().get(x).getEokerra1())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);
            } else if (jButton_erantzun2.getText().equals(p1.getGalderak().get(x).getEokerra2())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);
            }
        }
    }//GEN-LAST:event_jButton_erantzun2ActionPerformed

    private void jButton_erantzun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_erantzun3ActionPerformed
        // TODO add your handling code here:
        jLabelResult.setText("");
        jInternalFrame1.setVisible(false);
        for (int x = 0; x < p1.getGalderak().size(); x++) {
            if (jButton_erantzun3.getText().equals(p1.getGalderak().get(x).getEzuzena())) {
                play_ondo();
                jLabelResult.setText("Erantzun zuzena!!");
                jInternalFrame1.setVisible(true);
                p1.seteZuzenak(p1.geteZuzenak() + 1);
                p1.setRondak(p1.getRondak() + 1);
                p1.getGalderak().get(x).setAgertu(true);
                controlRondas();
                break;
            } else if (jButton_erantzun3.getText().equals(p1.getGalderak().get(x).getEokerra1())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);
            } else if (jButton_erantzun3.getText().equals(p1.getGalderak().get(x).getEokerra2())) {
                play_oker();
                jLabelResult.setText("Erantzun Okerra Saiatu berriro");
                jInternalFrame1.setVisible(true);
                p1.seteOkerrak(p1.geteOkerrak() + 1);

            }
        }
        
    }//GEN-LAST:event_jButton_erantzun3ActionPerformed

    public void play_ondo(){
        try {
            audioInputStream = AudioSystem.getAudioInputStream(archivomp3);            
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);            
            clip.start();
        } catch (LineUnavailableException | IOException| UnsupportedAudioFileException e) {
            System.err.println(e.getMessage());
        }
    } 
    public void play_oker(){
        try {
            audioInputStream = AudioSystem.getAudioInputStream(archivo_3);            
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);            
            clip.start();
        } catch (LineUnavailableException | IOException| UnsupportedAudioFileException e) {
            System.err.println(e.getMessage());
        }
    } 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p1.getUsr().addSaves(p1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Trivial2 prueba = new Trivial2();
                prueba.setVisible(true);
                prueba.setLocationRelativeTo(null);
                p1 = p1.getUsr().getLastSave();
                /**
                 * codigo aki
                 */
            }
        });


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    jInternalFrame1.setVisible(false);
    jInternalFrame1.hide();// TODO add your handling code here:
    jLabelResult.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButtonItzuliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItzuliActionPerformed
        play();// TODO add your handling code here:
        JFrame jokalariakFrame= new MenuJugadores();
        jokalariakFrame.setLocationRelativeTo(null);
        jokalariakFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonItzuliActionPerformed
    private void play(){
        try {
            audioInputStream = AudioSystem.getAudioInputStream(archivo_2);            
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);            
            clip.start();
        } catch (LineUnavailableException | IOException| UnsupportedAudioFileException e) {
            System.err.println(e.getMessage());
        }
    }
    private void jButtonPuntuazioaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntuazioaActionPerformed
        play();
        jPanel2.setVisible(true);
        jLabelEmaitzaJokalari.setText(p1.getUsr().getUname());
        jLabelEmaitzaZuzen.setText("" + p1.geteZuzenak());
        jLabelEmaitzaOker.setText("" + (p1.geteOkerrak()));
    }//GEN-LAST:event_jButtonPuntuazioaActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        /*jPanel2.setVisible(false);*/
        JFrame hasieraFrame= new Trivial1();
        hasieraFrame.setLocationRelativeTo(null);
        hasieraFrame.setVisible(true);
        prueba.dispose();
        this.hide();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trivial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trivial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trivial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trivial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Trivial2 prueba = new Trivial2();
                prueba.setVisible(true);
                prueba.setLocationRelativeTo(null);

                /**
                 * codigo aki
                 */
            }
        });
    }

    public void initialize() {
        //jokalariak initialize
        
        j1= MenuJugadores.getJ2();

        // galderak initialize
        g.add(new Galdera("Historia", "Zer Herrialde sortu zuten amerikar esklaboak Afrikan 1847. Urtean?", "Liberia", "Namibia", "Uganda"));
        g.add(new Galdera("Historia", "Nor izan zen Estatu Batuetako lehen lehendakaria?", "George Washington", "Abraham Lincoln", "Roosvelr"));
        g.add(new Galdera("Historia", "Zein urtetan zapaldu zuen gizakiak Ilargia lehen aldiz?", "1969an", "1967", "1970"));
        g.add(new Galdera("Historia", "Zein urtetan onartu zen emakumeen sufragioa Espainian?", "1931 urtean", "1950 urtean", "1985 urtean"));
        g.add(new Galdera("Historia", "Nor izan zen espainiar demokraziaren lehen lehendakaria frankismoaren ondoren?", "Adolfo Suarez", "Benito Lertxundi", "Aznar"));
        g.add(new Galdera("Historia", "Noiz inauguratu zen Londresko metroa?", "1863", "1963", "1873"));
        g.add(new Galdera("Historia", "Zein izan zen independentzia lortu zuen bigarren herrialde amerikarra?", "Haiti", "Cuba", "Filipinas"));
        g.add(new Galdera("Historia", "Nor zen Erromako enperadorea Jesus Nazaretekoa hil zenean?", "Tiberio", "Socrates", "Julio"));
        g.add(new Galdera("Historia", "Nola du izena mundua bi zatitan banatzen duen lerro bertikal irudikariak?", "Greenwich", "Macarana", "Zeonbert"));
        g.add(new Galdera("Historia", "Zein hiritan elkarrizketatu ziren Hitler eta Franco?", "Hendaia", "Monaco", "Benidorm"));
        g.add(new Galdera("Kirolak", "Nor da Formula 1 txapelketa irabazi duen Espainian jaiotako pilotu bakarra?", "Fernando Alonso", "Marc Marquez", "Carlos Sainz"));
        g.add(new Galdera("Kirolak", "Non eta noiz ospatu zen futboleko lehen mundiala?", "1930eko uztailaren 13an Uruguain", "1935eko ekainaren 14an Uruguain", "1930eko uztailaren 15ean Paraguayn"));
        g.add(new Galdera("Kirolak", "Zein dira bost eraztun olinpikoen koloreak?", "Horia, Urdina, Beltza, Gorria eta Berdea", "Horia, Txuria, Beltza, Gorria eta Berdea", "Morea, txuria, Urdina, Gorria eta Horia"));
        g.add(new Galdera("Kirolak", "Zenbat jokalari daude boleibol talde batean?", "Sei", "Bost", "Zortzi"));
        g.add(new Galdera("Kirolak", "Zeinek irabazi du gehien Roland Garros titulua?", "Rafa Nadal", "Roger Federer", "Novak Đoković"));
        g.add(new Galdera("Kirolak", "Zer arte martzial da \"Thailandiako boxeoa\"?", "Muay thai-a", "Krav maga", "yuyitsu"));
        g.add(new Galdera("Kirolak", "Non asmatu zen Ping-Pong?", "Inglaterra", "China", "EEUU"));
        g.add(new Galdera("Kirolak", "Nor izan zen Moto GPko munduko txapelduna 2017an?", "Marc Marquez", "Dani Pedrosa", "Jorge Lorenzo"));
        g.add(new Galdera("Kirolak", "Non asmatu zen Futbola?", "Inglaterra", "Brasil", "Espainia"));
        g.add(new Galdera("Kirolak", "Zein da titulu gehien dituen NBAko taldea?", "Boston Celtics", "Los Angeles Lakers", "Cleveland Cavaliers"));
        g.add(new Galdera("Geografia", "Zein da munduko kontinenterik handiera? ", "Amerika", "Asia", "Afrika"));
        g.add(new Galdera("Geografia", "Zein da munduko mendirik altuena?", "Everest", "Kilimanjaro", "Anboto"));
        g.add(new Galdera("Geografia", "Zein da Brasileko hiriburua?", "Brasilia", "Rio de Janeiro", "Sao Paulo"));
        g.add(new Galdera("Geografia", "Zein herrialdetan daude Espartako hondakinak?", "Grezia", "Mexico", "Albania"));
        g.add(new Galdera("Geografia", "Zein herrialde da munduko bigarren handiena biztanleriari dagokionez?", "India", "Txina", "EEUU"));
        g.add(new Galdera("Geografia", "Zein herrialdetan hitz egiten da gehienbat tagalo hizkuntza? ", "Filipinasen", "Tanzanian", "Laosen"));
        /* g.add(new IrudiGaldera("nueva_zelanda.jpg", "Geografia", "Zein herrialdetakoa da bandera hori?", "Zelanda Berria", "Inglaterra", "Australia"));*/
        g.add(new Galdera("Geografia", "Zenbat kontinente daude Lurrean?", "Sei", "Bost", "Zazpi"));
        g.add(new Galdera("Geografia", "Zenbat ozeano daude Lurrean?", "Bost", "Sei", "Lau"));
        g.add(new Galdera("Geografia", "Zain da Lurreko zatirik lehorrena?", "Antartida", "Sahara desertua", "\"Valle de la Muerte\"(EEUU)"));
        g.add(new Galdera("Entretenimiento", "Zein musika-talde kantatzen zuen Mamma Mia-k", "ABBA", "Mecano", "Europe"));
        g.add(new Galdera("Entretenimiento", "Nola du izena Walt Disneyren \"La Sirenita\" filmeko karramarroa?", "Sebastian", "Julian", "Paco"));
        /* g.add(new IrudiGaldera("Jhon_lennon.jpg", "Entretenimiento", "Zein da?", "Jhon Lennon", "Mick Jagger", "Iggy Pop"));*/
 /*g.add(new IrudiGaldera("Sammy_Davis.jpg", "Entretenimiento", "Zein da?", "Sammy Davis jr.", "Neil Amstrong", "Barack Obama"));*/
        g.add(new Galdera("Entretenimiento", "Zein da SEGA-ko maskota?", "Sonic", "Rayo McQueen", "Mario"));
        /*g.add(new IrudiGaldera("Mortadelo.jpg", "Entretenimiento", "Nor da?", "Mortadelo", "Filemon", "Super Lopez"));*/
        g.add(new Galdera("Entretenimiento", "Zein urtetan estreinatu zen Disneyren \"Pinocho\" filma?", "1940", "1945", "1955"));
        g.add(new Galdera("Entretenimiento", "Nola deitzen da Indiana Jones sagako protagonista?", "Harrison Ford", "Silvester Stallone", "Keanu Reeves"));
        g.add(new Galdera("Entretenimiento", "Zeinek Protagonizatzen du Jhon Wick saga?", "Keanu Reeves (The god)", "Jason Stathan", "Chuck Norris"));
        g.add(new Galdera("Entretenimiento", "Zenbat urte zituen Michael Jacksonek hil zenean?", "50", "49", "55"));
        /*g.add(new IrudiGaldera("Boticelli.jpg", "ArteLiteratura", "Zeinek margotu zuen?", "Botticelli", "Tiziano", "Caravaggio"));*/
        g.add(new Galdera("ArteLiteratura", "Zein mendetan jaio zen Velazquez", "XVII. Mendean", "XVI. Mendean", "XVIII. Mendean"));
        /*g.add(new IrudiGaldera("imagenes/picasso.jpg", "ArteLiteratura", "Nola deitzen da goiko marrazkia?", "Gernika", "Las Señoritas de Avignon", "La mujer que llora"));*/
 /*g.add(new IrudiGaldera("gaudi.jpg", "ArteLiteratura", "Nor da?", "Antoni Gaudi", "Lorca", "Picasso"));*/
        g.add(new Galdera("ArteLiteratura", "Zein museotan dago Mona Lisa?", "Louvre", "Museo metropolitano", "Museo del Vaticano"));
        /* g.add(new IrudiGaldera("arte", "ArteLiteratura", "Hau artea da?", "Bai", "Ez", "Batzuentzat"));*/
        g.add(new Galdera("ArteLiteratura", "Zein mendetan hasi zen errenazimendua?", "XV. Mendean", "XVI. Mendean", "XIV. Mendean"));
        g.add(new Galdera("ArteLiteratura", "Artista hauetako zein da dadaismoaren eta surrealismoaren giltzarria?", "Max Ernst", "Jan van eyck", "Rafael"));
        g.add(new Galdera("ArteLiteratura", "Noiz jaio zen Goya?", "1746", "1846", "1946"));
        g.add(new Galdera("ArteLiteratura", "Nork margotu zuen La Mona Lisa?", "Leonardo da Vinci", "Caravaccio", "Rafael"));
        g.add(new Galdera("NaturaZientziak", "Nola esaten zaio izaki bizidunak osatzen dituen gutxieneko osagaiari?", "Zelula", "Atomo", "Mikrobio"));
        g.add(new Galdera("NaturaZientziak", "Eguzkia: ", "Izar bat da", "Planeta bat da", "Berezia da"));
        g.add(new Galdera("NaturaZientziak", "Zein dira DNAren base nitrogenatuak?", "Guanina,adenina,timina eta zitosina", "guanina, adenina, kriptonita eta zitosina", "azidoa, adenina, timina, zitosina"));
        g.add(new Galdera("NaturaZientziak", "Zer izen du Alnitak, Alnilam eta Mintaka izarrek gure planetatik ikusita marraztutako lerroak?", "Orionen gerrikoa osatzen dute", "Jupiterren gerrikoa osatzen dute", "Piscisen gerrikoa osatzen dute"));
        g.add(new Galdera("NaturaZientziak", "Asto baten eta behor baten arteko bidegurutzearen ondorengoari honela deitzen zaio:", "Mulo", "Interplaneta", "Zorikot"));
        g.add(new Galdera("NaturaZientziak", "Miligramo bat: ", "0.001 gramo da", "0.01 gramo da", "0.0001 gramo da"));
        g.add(new Galdera("NaturaZientziak", "Zein da argiaren abiadura?", "300,000km/s", "350,00km/s", "370,00km/s"));
        g.add(new Galdera("NaturaZientziak", "Zer asmatu zuen Alfred Nobelek, sari famatuei izena ematen dienak?", "Dinamita", "Polvora", "Guanina"));
        g.add(new Galdera("NaturaZientziak", "Zein da globulu gorrien funtzio nagusia?", "oxigenoa eramatea", "Zaurak osatzea", "odola izatea"));
        g.add(new Galdera("NaturaZientziak", "Zein norabidetan apuntatzen du iparrorratz baten orratzak?", "Iparraldea", "Hegoaldea", "Ekialdea"));
        /*
        g.add(new Galdera("PuraCalle", "Peta a la luna?","Como niño en la cuna", "Como rey en la tribuna", "Futura fortuna"));
        g.add(new Galdera("PuraCalle", "Porro mañanero?","Tonto el dia entero", "Pedorro el dia entero", "Fumao el dia entero"));
        g.add(new Galdera("PuraCalle", "Si después  de una ducha estas limpio,¿Como se ensucia la toalla?","Por guarro", "Por pringao", "Por ir fumao"));
        g.add(new Galdera("PuraCalle", "Si se te cae una barra de jabón al piso, ¿será que el jabón se ensucia o el piso se limpia?","El jabon se ensucia", "el piso se limpia", "Ambas son correctas"));
        g.add(new Galdera("PuraCalle", "Cuando te haces un mariachi la china antes o después?","Después", "Antes", "Da igual"));
        g.add(new Galdera("PuraCalle", "Si me como un chip de ordenador me convierto en un robot?","Si", "No", "Depende del chip"));
        g.add(new Galdera("PuraCalle", "Si haces el amor con una embarazada puedes embarazar al niño de dentro?","Si", "No", "No se sabe"));
        g.add(new IrudiGaldera("imagenes/","PuraCalle", "Cual coloca más?","Mari", "China", "Las 2 por igual"));
        g.add(new Galdera("PuraCalle", "Si te entran un blancon que tienes que hacer primero?","Un pei pa despues", "Fumarte un pei", "Comer algo"));
        g.add(new Galdera("PuraCalle", "Si te fumas 4 porros?","buen morau", "Es que vas burlau", "estas colgao"));
        g.add(new Galdera("PuraCalle", "Peta a la luna?","Como niño en la cuna", "Como rey en la tribuna", "Futura fortuna"));
        
         */
    }

    public static Jokalaria getJ1() {
        return j1;
    }

    public void createPartida() {
        for (int x = 0; x < LIMITE; x++) {
            int index = (int) (Math.random() * g.size());
            galderaSorta.add(g.get(index));
        }
        p1 = new Partida(MenuJugadores.getJ2(), galderaSorta, 0, 0);
    }

    public void controlRondas() {
        if (p1.getRondak() < LIMITE) {
            nextRonda();
        }else{
            jInternalFrame1.setVisible(false);
            erantzunakErakutsi();
        }
    }
    public void erantzunakErakutsi(){
        jLabel_jokIzena.setText(p1.getUsr().getUname());
        jLabel_zuzenak.setText("" + p1.geteZuzenak());
        jLabel_okerrak.setText("" + (p1.geteOkerrak()));
        if(p1.geteOkerrak() < p1.geteZuzenak()){
          jLabel_resMessage.setText("OSO ONDO EGIN DUZU!!");  
        }else if(p1.geteOkerrak() > p1.geteZuzenak()){
            jLabel_resMessage.setText("HURRENGOAN HOBETO!!");
        }
        
        jPanel_resultado.setVisible(true);
        
    }
    public void nextRonda() {
        int SENTINEL = 0;
        int index = 0;
        IrudiGaldera comp1 = new IrudiGaldera("", "", "", "", "", "");
        while (SENTINEL != 1) {
            index = (int) (Math.random() * LIMITE);

            if (p1.getGalderak().get(index).isAgertu() == false) {
                SENTINEL = 1;
            }
        }
        if (p1.getGalderak().get(index).getClass().equals(comp1)) {
            /*jLabelImg.setText(p1.getGalderak().get(index).getIrudia());*/
            IrudiGaldera galdera = new IrudiGaldera("", "", "", "", "", "");
            jLabelGaldera.setText(p1.getGalderak().get(index).getGaldera());
            galdera = (IrudiGaldera) p1.getGalderak().get(index);
            jLabelImg.setIcon(new ImageIcon(getClass().getClassLoader().getResource("gaudi.jpg")));
            jLabelImg.setVisible(true);

            int al = (int) Math.floor(Math.random() * (3 - 1 + 1) + (1));
            if (al == 1) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEzuzena());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEokerra2());
            } else if (al == 2) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEzuzena());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEokerra2());
            } else if (al == 3) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEokerra2());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEzuzena());
            }

        } else {
            jLabelGaldera.setText(p1.getGalderak().get(index).getGaldera());
            int al = (int) Math.floor(Math.random() * (3 - 1 + 1) + (1));
            if (al == 1) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEzuzena());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEokerra2());
            } else if (al == 2) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEzuzena());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEokerra2());
            } else if (al == 3) {
                jButton_erantzun1.setText(p1.getGalderak().get(index).getEokerra2());
                jButton_erantzun2.setText(p1.getGalderak().get(index).getEokerra1());
                jButton_erantzun3.setText(p1.getGalderak().get(index).getEzuzena());
            }
        }

    }

    public void agertuFalseatzailea() {
        for (Galdera index : p1.getGalderak()) {
            index.setAgertu(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonItzuli;
    private javax.swing.JButton jButtonPuntuazioa;
    private javax.swing.JButton jButton_erantzun1;
    private javax.swing.JButton jButton_erantzun2;
    private javax.swing.JButton jButton_erantzun3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmaitzaJokalari;
    private javax.swing.JLabel jLabelEmaitzaOker;
    private javax.swing.JLabel jLabelEmaitzaZuzen;
    private javax.swing.JLabel jLabelGaldera;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabel_amaieraText;
    private javax.swing.JLabel jLabel_jokIzena;
    private javax.swing.JLabel jLabel_okerrak;
    private javax.swing.JLabel jLabel_puntuazioaText;
    private javax.swing.JLabel jLabel_resMessage;
    private javax.swing.JLabel jLabel_zuzenak;
    private javax.swing.JLabel jLabel_zuzenakText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_resultado;
    // End of variables declaration//GEN-END:variables
}
